### ISSUE TITLE
Pass GameTime into GameUpdate and GamePostUpdate Hooks

### ISSUE THREAD

**Issue by Arthri** [NyxStudios/TerrariaAPI-Server#180]
GameTime should be passed into both hooks, it allows for telling the passing of time easier

**Comment by hakusaro** [comment]
This seems reasonable.

**Comment by kevzhao2** [comment]
`GameTime` is defaulted in the `Update` method, so there is no value to doing this.

**Comment by Arthri** [comment]
Oh yeah
